# Generated by Django 4.0.2 on 2022-11-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_remove_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
